### ISSUE TITLE
Handle outcomes that don't have body text

### ISSUE THREAD

**Issue by chrisroos** [alphagov/smartanswer-to-smartdown#5]
The tool currently fails if you try to convert a Smart Answer that has an outcome without a body attribute.

```
$ bundle exec ./bin/smartanswer-to-smartdown ../smart-answers/lib/smart_answer_flows/inherits-someone-dies-without-will.rb sa-converted

/Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/model/outcome_block.rb:24:in `with_precalculations': undefined method `gsub' for nil:NilClass (NoMethodError)
    from /Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/model/outcome_block.rb:15:in `body'
    from /Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/smartanswer_to_smartdown.rb:48:in `generate_outcome'
    from /Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/smartanswer_to_smartdown.rb:25:in `block (2 levels) in call'
    from /Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/smartanswer_to_smartdown.rb:85:in `block in write_file'
    from /Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/smartanswer_to_smartdown.rb:84:in `open'
    from /Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/smartanswer_to_smartdown.rb:84:in `write_file'
    from /Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/smartanswer_to_smartdown.rb:25:in `block in call'
    from /Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/smartanswer_to_smartdown.rb:22:in `each'
    from /Users/chrisroos/Code/alphagov/smartanswer-to-smartdown/lib/smartanswer_to_smartdown.rb:22:in `call'
    from ./bin/smartanswer-to-smartdown:21:in `<main>'
```

**Comment by chrisroos** [comment]
You appear to be able to solve this particular problem by returning early from `Model::OutcomeBlock#with_precalculations` if the body doesn't exist. Add `return unless body` as the first line in that method.
